/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gráfico;
import javax.swing.JOptionPane;

/**
 *
 * @author Aprendiz
 */
public class Fsueldo extends javax.swing.JInternalFrame {
   

    /**
     * Creates new form Fsueldo
     */
    public Fsueldo() {
        initComponents();
       
    }
     double mayor=0,menor=9999999,sueldototal=0,csueldo=0;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Sueldo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        calcular = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Area = new javax.swing.JTextArea();
        borrar = new javax.swing.JButton();
        salir = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jLabel1.setText("Digite un numero");

        calcular.setText("Calcular");
        calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcularActionPerformed(evt);
            }
        });

        Area.setColumns(20);
        Area.setRows(5);
        jScrollPane1.setViewportView(Area);

        borrar.setText("Borrar");
        borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarActionPerformed(evt);
            }
        });

        salir.setText("salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel1)
                        .addGap(40, 40, 40)
                        .addComponent(Sueldo))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(borrar)
                        .addComponent(calcular, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(salir))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Sueldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 38, Short.MAX_VALUE)
                        .addComponent(calcular)
                        .addGap(18, 18, 18)
                        .addComponent(borrar)
                        .addGap(18, 18, 18)
                        .addComponent(salir)
                        .addGap(54, 54, 54))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void calcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcularActionPerformed
       double sueldo, promedio, getsueldo;
        
        sueldo=Double.valueOf(Sueldo.getText());
        Clases.Sueldo obj1= new Clases.Sueldo(sueldo);
        getsueldo=obj1.getsueldo();
        csueldo++;
       if(csueldo==1){
           mayor=getsueldo;
           menor=getsueldo;
       } else if(getsueldo>menor){
           mayor=getsueldo;
           
           	
       }else{
           menor=getsueldo;
          
       }
        sueldototal=sueldototal+getsueldo;
        promedio=sueldototal/csueldo;
        
       
        Area.setText("Sueldos Ingresados :" + csueldo+"\n");
        Area.append("Sueldo mayor :" + mayor+"\n");
        Area.append("Sueldo menor :" + menor+"\n");
        Area.append("Promedio :" + promedio+"\n");
      
    }//GEN-LAST:event_calcularActionPerformed

    private void borrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarActionPerformed
        String mensaje= " ";
        Sueldo.setText(mensaje);
        Area.setText(mensaje);
    }//GEN-LAST:event_borrarActionPerformed
    
    
    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        
      int resp=JOptionPane.showConfirmDialog(null,"¿Deseas salir?");
      if (JOptionPane.OK_OPTION == resp){
    System.out.println("Selecciona opción Afirmativa");
    JOptionPane.showMessageDialog(null,"Pudimos haber vivido mas momentos felices, pero gracias por despreciarme"); 
      System.exit(0);
      }
      else{
    System.out.println("No selecciona una opción afirmativa");
    JOptionPane.showMessageDialog(null,"Esooooo, Gracias por quedarte!!!"); 
      }
        
     
    }//GEN-LAST:event_salirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Area;
    private javax.swing.JTextField Sueldo;
    private javax.swing.JButton borrar;
    private javax.swing.JButton calcular;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton salir;
    // End of variables declaration//GEN-END:variables
}
