/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gráfico;

/**
 *
 * @author Familia
 */
public class Licencias extends javax.swing.JInternalFrame {

    /**
     * Creates new form Licencias
     */
    public Licencias() {
        initComponents();
    }
    int total,importec,importeb,importep,importeg,lcobre,lbronce,lplata,lgold,licenciasc,licenciasb,licenciasp,licenciasg;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tipos = new javax.swing.JComboBox<>();
        proce = new javax.swing.JButton();
        borrar = new javax.swing.JButton();
        licencia = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        actual = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        historico = new javax.swing.JTextArea();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jLabel1.setText("Tipo de licencia");

        jLabel2.setText("Número de licencia");

        tipos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Cobre", "Bronce", "Silver", "Gold" }));
        tipos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tiposActionPerformed(evt);
            }
        });

        proce.setText("Procesar");
        proce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proceActionPerformed(evt);
            }
        });

        borrar.setText("Borrar");
        borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarActionPerformed(evt);
            }
        });

        jLabel3.setText("                                                   Venta actual");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        actual.setColumns(20);
        actual.setRows(5);
        jScrollPane1.setViewportView(actual);

        jLabel4.setText("                                                  Reporte histórico");
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        historico.setColumns(20);
        historico.setRows(5);
        jScrollPane2.setViewportView(historico);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tipos, 0, 128, Short.MAX_VALUE)
                            .addComponent(licencia))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(proce, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(borrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(32, 32, 32))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tipos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(proce))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(licencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(borrar))
                    .addComponent(jLabel2))
                .addGap(19, 19, 19)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tiposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tiposActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tiposActionPerformed

    private void proceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proceActionPerformed
        int tipo, cantidad, getcanti;
        tipo=tipos.getSelectedIndex();
        cantidad=Integer.valueOf(licencia.getText());
        Clases.Licencia opc=new Clases.Licencia(tipo,cantidad);
        getcanti=opc.getCantidad();
          switch(tipo){
           case 0:
               actual.append("Seleccione una opción");
               break;
           case 1:
               lcobre++;
               total=getcanti*510;
               importec=importec+total;
               licenciasc=licenciasc+getcanti;
               break;
               case 2:
               lbronce++;    
               total=getcanti*1500;
               importeb=importeb+total;
               licenciasb=licenciasb+getcanti;
               break;
               case 3:
               lplata++;    
               total=getcanti*3100;
               importep=importep+total;
               licenciasp=licenciasp+getcanti;
               break;
              case 4:
               lgold++;   
               total=getcanti*4500;
               importeg=importeg+total;
               licenciasg=licenciasg+getcanti;
               break; 
          }
            String mensaje="";
            actual.setText(mensaje);
            historico.setText(mensaje);
            
            actual.append("Tipo de licencia: "+tipos.getSelectedItem()+"\n");
            actual.append("Numero de licencia: "+getcanti+"\n");
            actual.append("Importe a pagar: "+total+"\n");
            historico.append("Numero de licencias vendidas"+"\n");
            historico.append("Licencia Cobre: "+licenciasc+"\n");
            historico.append("Licencia Bronze: "+licenciasb+"\n");
            historico.append("Licencia Silver: "+licenciasp+"\n");
            historico.append("Licencia Gold: "+licenciasg+"\n");
            historico.append("Numero de ventas efectuadas"+"\n");
            historico.append("Licencia Cobre: "+lcobre+"\n");
            historico.append("Licencia Bronze: "+lbronce+"\n");
            historico.append("Licencia Silver: "+lplata+"\n");
            historico.append("Licencia Gold: "+lgold+"\n");
            historico.append("Ganancia neta"+"\n");
            historico.append("Licencia Cobre: "+importec+"\n");
            historico.append("Licencia Bronze: "+importeb+"\n");
            historico.append("Licencia Silver: "+importep+"\n");
            historico.append("Licencia Gold: "+importeg+"\n");
            
            
            
    }//GEN-LAST:event_proceActionPerformed

    private void borrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarActionPerformed
      String mensaje="";
            actual.setText(mensaje);
            historico.setText(mensaje);
    }//GEN-LAST:event_borrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea actual;
    private javax.swing.JButton borrar;
    private javax.swing.JTextArea historico;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField licencia;
    private javax.swing.JButton proce;
    private javax.swing.JComboBox<String> tipos;
    // End of variables declaration//GEN-END:variables
}
