/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gráfico;

/**
 *
 * @author Familia
 */
public class Peaje extends javax.swing.JInternalFrame {

    /**
     * Creates new form Peaje
     */
    public Peaje() {
        initComponents();
    }
int auto=0,camion=0,camioneta=0,omni=0,otro=0,autoacu,camionacu,camionetaacu,omniacu,otroacu;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        canti = new javax.swing.JTextField();
        seleccion = new javax.swing.JComboBox<>();
        registro = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        area = new javax.swing.JTextArea();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jLabel1.setText("Tipo de vehículo");

        jLabel2.setText("Cantidad de pasajeros");

        seleccion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Automóvil", "Camión", "Camioneta", "Ómnibus", "Otro" }));

        registro.setText("Registrar");
        registro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registroActionPerformed(evt);
            }
        });

        area.setColumns(20);
        area.setRows(5);
        jScrollPane1.setViewportView(area);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(seleccion, 0, 121, Short.MAX_VALUE)
                            .addComponent(canti))
                        .addGap(18, 18, 18)
                        .addComponent(registro))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(seleccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(canti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(registro)
                        .addGap(21, 21, 21)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registroActionPerformed
       int cantidad,tipo,getcanti;
       cantidad=Integer.valueOf(canti.getText());
       tipo=seleccion.getSelectedIndex();
       Clases.Peaje opc=new Clases.Peaje(tipo,cantidad);
       getcanti=opc.getCantidad();
      
       switch(tipo){
           case 0:
               area.append("Seleccione una opción");
               break;
           case 1:
              auto++;
              autoacu=autoacu+getcanti;
               break;
           case 2: 
               camion++;
               camionacu=camionacu+getcanti;
               break;
           case 3: 
               camioneta++;
               camionetaacu=camionetaacu+getcanti;
               break;
           case 4:
               omni++;
               omniacu=omniacu+getcanti;
               break;
           case 5:
               otro++;
               otroacu=otroacu+getcanti;
               break;
                   }        
       String mensaje2=" ";
       area.setText(mensaje2);
        area.append("Vehículo"+"\tCantidad\tPasajeros"+"\n");
        area.append("Automóvil"+"\t"+auto+"\t"+autoacu+"\n");
        area.append("Camión"+"\t"+camion+"\t"+camionacu+"\n");
        area.append("Camioneta"+"\t"+camioneta+"\t"+camionetaacu+"\n");
        area.append("Ómnibus"+"\t"+omni+"\t"+omniacu+"\n");
        area.append("Otro"+"\t"+otro+"\t"+otroacu+"\n");
       
    }//GEN-LAST:event_registroActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea area;
    private javax.swing.JTextField canti;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton registro;
    private javax.swing.JComboBox<String> seleccion;
    // End of variables declaration//GEN-END:variables
}
