package gráfico;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Aprendiz
 */
public class Tienda2 extends javax.swing.JInternalFrame {

    /**
     * Creates new form Tienda2
     */
    public Tienda2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        calcular = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cantidad = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        resultado = new javax.swing.JTextArea();
        codigo = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        vaciar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        calcular.setText("Calcular");
        calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcularActionPerformed(evt);
            }
        });

        jLabel1.setText("Cantidad");

        resultado.setColumns(20);
        resultado.setRows(5);
        jScrollPane1.setViewportView(resultado);

        codigo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "101", "102", "103" }));

        jLabel2.setText("Codigo");

        vaciar.setText("Vaciar");
        vaciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vaciarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(codigo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cantidad))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(calcular)
                        .addGap(4, 4, 4)))
                .addContainerGap(35, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(vaciar)
                .addGap(159, 159, 159))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)))
                    .addComponent(calcular, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(vaciar)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void calcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcularActionPerformed
       double descu,total,total2;
       int m,Cantid,codigo1;
       codigo1=codigo.getSelectedIndex();
       Cantid=Integer.parseInt(cantidad.getText());
        
       Clases.Tiendas2 opc=new Clases.Tiendas2 (Cantid,codigo1);
       m=opc.getCodigo();
       Cantid=opc.getCantidad();
    switch (m){
    case 0:
        if (Cantid>=1 && Cantid<=10){
            total=Cantid*17.5;
            descu=total*0.05;
            total2=total-descu;
            resultado.append("El valor de su compra es: "+total+"\n"+" sin embargo usted tiene un descuento del: "+descu+"\n"+" por lo tanto tu compra esta por: "+total2);
        }
        else if (Cantid>=11 && Cantid<=20){
            total=Cantid*17.5;
            descu=total*0.05;
            total2=total-descu;
            resultado.append("El valor de su compra es: "+total+"\n"+" sin embargo usted tiene un descuento del: "+descu+"\n"+" por lo tanto tu compra esta por: "+total2);
        }
    else if (Cantid>=21 ){
            total=Cantid*17.5;
            descu=total*0.05;
            total2=total-descu;
            resultado.append("El valor de su compra es: "+total+"\n"+" sin embargo usted tiene un descuento del: "+descu+"\n"+" por lo tanto tu compra esta por: "+total2);
        }
    
    break;
    case 1:
            if (Cantid>=1 && Cantid<=10){
            total=Cantid*25.0;
            descu=total*0.075;
            total2=total-descu;
            resultado.append("El valor de su compra es: "+total+"\n"+" sin embargo usted tiene un descuento del: "+descu+"\n"+" por lo tanto tu compra esta por: "+total2);
        }
        else if (Cantid>=11 && Cantid<=20){
            total=Cantid*25.0;
            descu=total*0.075;
            total2=total-descu;
            resultado.append("El valor de su compra es: "+total+"\n"+" sin embargo usted tiene un descuento del: "+descu+"\n"+" por lo tanto tu compra esta por: "+total2);
        }
    else if (Cantid>=21 ){
            total=Cantid*25.0;
            descu=total*0.075;
            total2=total-descu;
            resultado.append("El valor de su compra es: "+total+"\n"+" sin embargo usted tiene un descuento del: "+descu+"\n"+" por lo tanto tu compra esta por: "+total2);
        }
    break;
    case 2:
          if (Cantid>=1 && Cantid<=10){
            total=Cantid*15.5;
            descu=total*0.1;
            total2=total-descu;
            resultado.append("El valor de su compra es: "+total+"\n"+" sin embargo usted tiene un descuento del: "+descu+"\n"+" por lo tanto tu compra esta por: "+total2);
        }
        else if (Cantid>=11 && Cantid<=20){
            total=Cantid*15.5;
            descu=total*0.1;
            total2=total-descu;
            resultado.append("El valor de su compra es: "+total+"\n"+" sin embargo usted tiene un descuento del: "+descu+"\n"+" por lo tanto tu compra esta por: "+total2);
        }
    else if (Cantid>=21 ){
            total=Cantid*15.5;
            descu=total*0.1;
            total2=total-descu;
            resultado.append("El valor de su compra es: "+total+"\n"+" sin embargo usted tiene un descuento del: "+descu+"\n"+" por lo tanto tu compra esta por: "+total2);
        }
    break;
   
}   
    }//GEN-LAST:event_calcularActionPerformed

    private void vaciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vaciarActionPerformed
        String mensaje= " ";  
        resultado.setText(mensaje);
    }//GEN-LAST:event_vaciarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton calcular;
    private javax.swing.JTextField cantidad;
    private javax.swing.JComboBox codigo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea resultado;
    private javax.swing.JButton vaciar;
    // End of variables declaration//GEN-END:variables
}
